from django.urls import path
from dashboard import views

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='dashboard'),
    path('asset/request/',
         views.AssetRequestBarChartView.as_view(), name='asset_request_bar'),
    path('asset-list/', views.AssetListView.as_view(), name="asset_list"),
    path('asset-form/', views.AssetCreateView.as_view(), name="asset_form"),
    path('asset-update/<pk>/',
         views.AssetUpdateView.as_view(), name="asset_update"),
    path('asset-delete/<pk>/',
         views.AssetDeleteView.as_view(), name="asset_delete"),
    path('asset-status-list/',
         views.AssetStatusListView.as_view(), name="asset_status_list"),
    path('asset-status-new/',
         views.AssetStatusCreateView.as_view(), name="asset_status_new"),
    path('asset-status-update/<pk>/',
         views.AssetStatusUpdateView.as_view(), name="asset_status_update"),
    path('asset-status-delete/<pk>/',
         views.AssetStatusDeleteView.as_view(), name="asset_status_delete"),
    path('category-list/',
         views.CategoryListView.as_view(), name="category_list"),
    path('category-form/',
         views.CategoryCreateView.as_view(), name="category_form"),
    path('category-update/<pk>/',
         views.CategoryUpdateView.as_view(), name="category_update"),
    path('category-delete/<pk>/',
         views.CategoryDeleteView.as_view(), name="category_delete"),
    path('supplier-list/',
         views.SupplierListView.as_view(), name="supplier_list"),
    path('supplier-form/',
         views.SupplierCreateView.as_view(), name="supplier_form"),
    path('supplier-update/<pk>/',
         views.SupplierUpdateView.as_view(), name="supplier_update"),
    path('supplier-delete/<pk>/',
         views.SupplierDeleteView.as_view(), name="supplier_delete"),
    path('department-list/',
         views.DepartmentListView.as_view(), name="department_list"),
    path('department-form/',
         views.DepartmentCreateView.as_view(), name="department_form"),
    path('department-update/<pk>/',
         views.DepartmentUpdateView.as_view(), name="department_update"),
    path('department-delete/<pk>/',
         views.DepartmentDeleteView.as_view(), name="department_delete"),
    path('asset-request-list/',
         views.AssetRequestListView.as_view(), name="asset_request_list"),
    path('asset-request-update/<pk>/',
         views.AssetRequestUpdateView.as_view(), name="asset_request_update"),
    path('asset-request-delete/<pk>/',
         views.AssetRequestDeleteView.as_view(), name="asset_request_delete"),
    path('asset-issue-list/',
         views.AssetIssueListView.as_view(), name="asset_issue_list"),
    path('asset-issue-form/',
         views.AssetIssueCreateView.as_view(), name="asset_issue_form"),
    path('asset-issue-update/<pk>/',
         views.AssetIssueUpdateView.as_view(), name="asset_issue_update"),
    path('asset-issue-delete/<pk>/',
         views.AssetIssueDeleteView.as_view(), name="asset_issue_delete"),
]
